# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/apps/c-cpp/gcc
# adding a comment

jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - script: |
      make
    displayName: 'make'
- job: macOS
  pool:
    vmImage: 'macOS 11'
  steps:
  - script: |
      make
    displayName: 'make'
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      cmake
    displayName: 'nmake'
